/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projek.rpl;

/**
 *
 * @author User
 */
import java.sql.*;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class Menu extends javax.swing.JFrame {
    Statement stmt;
    Connection con;
    String url = "jdbc:mysql://localhost:3306/tugas_akhirRPL";
    PreparedStatement pst;
    ResultSet res;
    
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        tampil1();

        tampil3();
    }
    
    public void kosong(){
        kodeTF.setText("");
        jenis_hidanganJB.setSelectedItem("");
        nama_makananTF.setText("");
        jumlahTF.setText("");
        hargaTF.setText("");
    }
    

    
    public void tampil1(){
                    try{
            con=DriverManager.getConnection(url,"root","");
             System.out.println("Database ditemukan");

            pst = con.prepareStatement("select *from menu");
            res = pst.executeQuery();
            ResultSetMetaData results = res.getMetaData();   
            int j = results.getColumnCount();
            
            DefaultTableModel df = (DefaultTableModel)dataTB.getModel();
            df.setRowCount(0);
            while(res.next()) {
                Vector vx = new Vector();
                for(int i = 1; i <= j; i++) {
                    vx.add(res.getString("kd_menu"));
                    vx.add(res.getString("jenis"));
                    vx.add(res.getString("nama_makanan"));
                    vx.add(res.getString("kuantitas"));
                    vx.add(res.getString("harga"));
                }
                df.addRow(vx);
            }
        }catch(SQLException ex){
            System.err.println("SQLException:" + ex.getMessage());
            
        }
    }
    
        public void tampil2(){
                    try{
            con=DriverManager.getConnection(url,"root","");
             System.out.println("Database ditemukan");

            pst = con.prepareStatement("select kd_menu, no_meja, pemesan,jenis,nama_makanan, kuantitas, harga from transaksi");
            res = pst.executeQuery();
            ResultSetMetaData results = res.getMetaData();   
            int j = results.getColumnCount();
            
            DefaultTableModel df = (DefaultTableModel)data2TB.getModel();
            df.setRowCount(0);
            while(res.next()) {
                Vector vx = new Vector();
                for(int i = 1; i <= j; i++) {
                    vx.add(res.getString("kd_menu"));
                    vx.add(res.getString("no_meja"));
                    vx.add(res.getString("pemesan"));
                    vx.add(res.getString("jenis"));
                    vx.add(res.getString("nama_makanan"));
                    vx.add(res.getString("kuantitas"));
                    vx.add(res.getString("harga"));
                }
                df.addRow(vx);
            }
        }catch(SQLException ex){
            System.err.println("SQLException:" + ex.getMessage());
            
        }
    }
        
        public void tampil3(){
                                try{
            con=DriverManager.getConnection(url,"root","");
             System.out.println("Database ditemukan");

            pst = con.prepareStatement("select *from laporan");
            res = pst.executeQuery();
            ResultSetMetaData results = res.getMetaData();   
            int j = results.getColumnCount();
            
            DefaultTableModel df = (DefaultTableModel)laporan.getModel();
            df.setRowCount(0);
            while(res.next()) {
                Vector vx = new Vector();
                for(int i = 1; i <= j; i++) {
                    vx.add(res.getString("tanggal"));
                    vx.add(res.getString("bulan"));
                    vx.add(res.getString("tahun"));
                    vx.add(res.getString("kd_menu"));
                    vx.add(res.getString("jenis"));
                    vx.add(res.getString("pemesan"));
                    vx.add(res.getString("nama_makanan"));
                    vx.add(res.getString("kuantitas"));
                    vx.add(res.getString("harga"));
                }
                df.addRow(vx);
            }
        }catch(SQLException ex){
            System.err.println("SQLException:" + ex.getMessage());
            
        }
        }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        dataTB = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        data2TB = new javax.swing.JTable();
        cariTF = new javax.swing.JTextField();
        cariBT = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        kodeTF = new javax.swing.JTextField();
        nama_makananTF = new javax.swing.JTextField();
        hargaTF = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        tambahBT = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        no_mejaTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        pemesanTF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        totalTF = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        hasilTF = new javax.swing.JTextField();
        uangTF = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        kd_menu2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        kuantitas2TF = new javax.swing.JTextField();
        hapus2bt = new javax.swing.JButton();
        jumlahTF = new javax.swing.JTextField();
        hapusBT = new javax.swing.JButton();
        bulanJB = new javax.swing.JComboBox<>();
        tanggalJB = new javax.swing.JComboBox<>();
        tahunJB = new javax.swing.JComboBox<>();
        jenis_hidanganJB = new javax.swing.JComboBox<>();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        laporan = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        cari2TF = new javax.swing.JTextField();
        jComboBox6 = new javax.swing.JComboBox<>();
        cari2BT = new javax.swing.JButton();
        hapusbt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane2.setBackground(new java.awt.Color(35, 52, 108));

        dataTB.setBackground(new java.awt.Color(63, 137, 202));
        dataTB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dataTB.setForeground(new java.awt.Color(34, 66, 141));
        dataTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "KODE MENU", "JENIS", "NAMA", "KUANTITAS", "HARGA"
            }
        ));
        dataTB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataTBMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(dataTB);

        jLabel2.setFont(new java.awt.Font("Yu Mincho Light", 0, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("RESTORAN WAKA");

        jPanel1.setBackground(new java.awt.Color(34, 66, 141));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 29)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("UPDATE MENU");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(596, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(560, 560, 560))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(34, 66, 141));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 29)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DAFTAR MENU");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(564, 564, 564))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        data2TB.setBackground(new java.awt.Color(63, 137, 202));
        data2TB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "KODE MENU", "NO MEJA", "PEMESAN", "JENIS", "NAMA", "KUANTITAS", "HARGA"
            }
        ));
        data2TB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                data2TBMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(data2TB);

        cariTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariTFActionPerformed(evt);
            }
        });

        cariBT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cariBT.setText("CARI");
        cariBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariBTActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(34, 66, 141));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 29)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TRANSAKSI");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("KODE MENU");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NAMA HIDANGAN");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("KUANTITAS");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("JENIS HIDANGAN");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("HARGA");

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tambahBT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tambahBT.setText("TAMBAH");
        tambahBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBTActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(63, 137, 202));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("NO MEJA");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("TOTAL");

        totalTF.setBackground(new java.awt.Color(102, 126, 206));

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton4.setText("TAMBAH");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("KUANTITAS");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("JUMLAH UANG");

        hasilTF.setBackground(new java.awt.Color(102, 126, 206));

        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton6.setText("HITUNG");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("KODE MENU");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("PEMESAN");

        kuantitas2TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kuantitas2TFActionPerformed(evt);
            }
        });

        hapus2bt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hapus2bt.setText("HAPUS");
        hapus2bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapus2btActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hasilTF, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(49, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(hapus2bt, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(no_mejaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(kd_menu2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pemesanTF, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(kuantitas2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(totalTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uangTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(kd_menu2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(no_mejaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(pemesanTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(kuantitas2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(hapus2bt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uangTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hasilTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        hapusBT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hapusBT.setText("HAPUS");
        hapusBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBTActionPerformed(evt);
            }
        });

        bulanJB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Okotober", "November", "Desember", " " }));

        tanggalJB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32" }));

        tahunJB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027" }));

        jenis_hidanganJB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jenis_hidanganJB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MAKANAN", "MINUMAN", " " }));

        jDesktopPane2.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(cariTF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(cariBT, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(kodeTF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(nama_makananTF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(hargaTF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(tambahBT, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jumlahTF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(hapusBT, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(bulanJB, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(tanggalJB, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(tahunJB, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jenis_hidanganJB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(408, 408, 408)
                        .addComponent(tanggalJB, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bulanJB, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tahunJB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                        .addGap(85, 85, 85)
                                        .addComponent(hapusBT, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cariTF, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cariBT, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                    .addGap(105, 105, 105)
                                    .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel9))
                                    .addGap(50, 50, 50)
                                    .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nama_makananTF, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                            .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(kodeTF)
                                                .addComponent(jenis_hidanganJB, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(201, 201, 201)
                                            .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                                    .addComponent(jLabel8)
                                                    .addGap(75, 75, 75)
                                                    .addComponent(jumlahTF, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                                                    .addComponent(jLabel10)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                                            .addComponent(tambahBT, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(hargaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3))
                            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bulanJB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tanggalJB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tahunJB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                                .addComponent(cariBT)
                                .addComponent(cariTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(hapusBT))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(kodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlahTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(32, 32, 32)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jenis_hidanganJB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)))
                            .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(hargaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)))
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(nama_makananTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton2)
                                    .addComponent(tambahBT)))))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("BERANDA", jDesktopPane2);

        jDesktopPane1.setBackground(new java.awt.Color(35, 52, 108));

        laporan.setBackground(new java.awt.Color(63, 137, 202));
        laporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "TANGGAL", "BULAN", "TAHUN", "KODE MENU", "NO MEJA", "JENIS", "PEMESAN", "NAMA", "KUANTITAS", "TOTAL HARGA"
            }
        ));
        laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(laporan);

        jLabel16.setFont(new java.awt.Font("Yu Mincho Light", 0, 50)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("RESTORAN WAKA");

        cari2TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari2TFActionPerformed(evt);
            }
        });

        jComboBox6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32" }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });

        cari2BT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cari2BT.setText("CARI");
        cari2BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari2BTActionPerformed(evt);
            }
        });

        hapusbt.setText("Hapus");
        hapusbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusbtActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(cari2TF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jComboBox6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(cari2BT, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(hapusbt, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hapusbt)
                        .addGap(107, 107, 107)
                        .addComponent(cari2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cari2BT, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1893, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(741, 741, 741)
                .addComponent(jLabel16)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cari2BT)
                    .addComponent(cari2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hapusbt))
                .addContainerGap(294, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("LAPORAN", jDesktopPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("MENU");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cariTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariTFActionPerformed

    private void cari2TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari2TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cari2TFActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    String kd_menu =kodeTF.getText();
        String jenis_hidangan = (String)jenis_hidanganJB.getSelectedItem();
        String nama_makanan = nama_makananTF.getText();
        String jumlah = jumlahTF.getText();
        int kuantitas = Integer.parseInt(jumlah);
        String harga = hargaTF.getText();
        int total = Integer.parseInt(harga);
        
        try{
            con=DriverManager.getConnection(url,"root","");
             System.out.println("Database ditemukan");
            stmt = con.createStatement();
           String sql =  "update menu set jenis='"+jenis_hidangan+"',nama_makanan='"+nama_makanan+"',kuantitas='"+kuantitas+"',harga='"+total+"'where kd_menu='" +kd_menu+"'";
 //           String sql = "update menu set kd_menu ='"+kodeTF +"', jenis='"+jenis_hidanganJB+", nama_makanan='"+nama_makananTF+"', kuantitas='"+jumlahTF+"', harga='"+hargaTF+"' where kd_menu ='" +kodeTF +"'";

//            String sql = "insert into menu values('"+kd_menu+"','"+jenis_hidangan+"','"+nama_makanan+"','"+kuantitas+"','"+total+"')";
            stmt.executeUpdate(sql);
            tampil1();
           JOptionPane.showMessageDialog(this, "Perubahan Telah DIsimpan");


//con = DriverManager.getConnection(url,"root","");
//            System.out.println("Database ditemukan");
//            
//            String sql = "UPDATE kendaraan_masuk SET nama=?,jenis_kendaraan=?,tipe_kendaraan=?,tanggal=?,jam=? WHERE nomor_kendaraan=?";
//            PreparedStatement Pstatement = con.prepareStatement(sql);
//            
//           
//            Pstatement.setString(1, kodeTF.getText());
//            Pstatement.setString(2, (String)jenis_hidanganJB.getSelectedItem());
//            Pstatement.setString(3, nama_makananTF.getText());
//            Pstatement.setString(4, tanggalTF.getText());
//            Pstatement.setString(5, jamTF.getText());
//            Pstatement.setString(6, noTF.getText());

            
        }catch(SQLException ex){
            System.err.println("SQLException:" + ex.getMessage());
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void tambahBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBTActionPerformed
        // TODO add your handling code here:
        String kd_menu =kodeTF.getText();
        String jenis_hidangan = (String)jenis_hidanganJB.getSelectedItem();
        String nama_makanan = nama_makananTF.getText();
        String jumlah = jumlahTF.getText();
        int kuantitas = Integer.parseInt(jumlah);
        String harga = hargaTF.getText();
        int total = Integer.parseInt(harga);
        
        try{
            con=DriverManager.getConnection(url,"root","");
             System.out.println("Database ditemukan");
            stmt = con.createStatement();
            String sql = "insert into menu values('"+kd_menu+"','"+jenis_hidangan+"','"+nama_makanan+"','"+kuantitas+"','"+total+"')";
            stmt.executeUpdate(sql);
            tampil1();
            kosong();
            
            
   
        }catch(SQLException ex){
            System.err.println("SQLException:" + ex.getMessage());
            
        }
        
    }//GEN-LAST:event_tambahBTActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        
        
        String kd_menu = kd_menu2.getText();
        String no_meja = no_mejaTF.getText();
        String pemesan = pemesanTF.getText();
        String kuantitas = kuantitas2TF.getText();
        int jumlah = Integer.parseInt(kuantitas);
        String jenis = "";
        String nama_makanan = "";
        int harga =0;
        
        
        
        try{
            con=DriverManager.getConnection(url,"root","");
             System.out.println("Database ditemukan");
            stmt = con.createStatement();
            
            
            
            String sql2="select jenis, nama_makanan, harga from menu where kd_menu='"+kd_menu2.getText()+"'";
            res = stmt.executeQuery(sql2);
            
            while(res.next()){
                jenis = res.getString("jenis");
                nama_makanan = res.getString("nama_makanan");
                harga = res.getInt("harga");
            }
            
            String sql = "insert into transaksi values('"+kd_menu+"','"+no_meja+"','"+pemesan+"','"+jenis+"','"+nama_makanan+"','"+jumlah+"','"+harga*jumlah+"')";
            stmt.executeUpdate(sql);
            tampil2();
            
            
            String sql3 ="Select SUM(harga) as total_harga from transaksi";
            res = stmt.executeQuery(sql3);
            int total_harga =0;
            
            while(res.next()){
                total_harga = res.getInt("total_harga");
              
            }
            totalTF.setText(Integer.toString(total_harga));
//            String total_harga2 = Integer.toString(total_harga1);
//            totalTF.setText(total_harga2);
            
                 kd_menu2.setText("");
                 kuantitas2TF.setText("");
            
            
   
        }catch(SQLException ex){
            System.err.println("SQLException:" + ex.getMessage());
      
            
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void dataTBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataTBMouseClicked
        int baris = dataTB.rowAtPoint(evt.getPoint());
        String  kd_menu = dataTB.getValueAt(baris, 0).toString();
        kodeTF.setText(kd_menu);
        kd_menu2.setText(kd_menu);
        String  jenis_hidangan = dataTB.getValueAt(baris, 1).toString();
        jenis_hidanganJB.setSelectedItem(jenis_hidangan);
        String  nama_makanan = dataTB.getValueAt(baris, 2).toString();
        nama_makananTF.setText(nama_makanan);
        String  jumlah = dataTB.getValueAt(baris, 3).toString();
        jumlahTF.setText(jumlah);
        String  harga = dataTB.getValueAt(baris, 4).toString();
        hargaTF.setText(harga);
        
        
                
//                String kd_menu =kodeTF.getText();
//        String jenis_hidangan = (String)jenis_hidanganJB.getSelectedItem();
//        String nama_makanan = nama_makananTF.getText();
//        String jumlah = jumlahTF.getText();
//        int kuantitas = Integer.parseInt(jumlah);
//        String harga = hargaTF.getText();
//        int total = Integer.parseInt(harga);
    }//GEN-LAST:event_dataTBMouseClicked

    private void cariBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariBTActionPerformed
        // TODO add your handling code here:
                try{
            con = DriverManager.getConnection(url,"root","");

            String query = "SELECT * FROM menu WHERE concat(kd_menu, jenis, nama_makanan, kuantitas, harga) LIKE ? ESCAPE '!'";
            PreparedStatement pstm = con.prepareStatement(query);
            pstm.setString(1, "%" + cariTF.getText() + "%");
            res = pstm.executeQuery();
            
            ResultSetMetaData results = res.getMetaData();  
            int j = results.getColumnCount();
            
            DefaultTableModel df = (DefaultTableModel)dataTB.getModel();
            df.setRowCount(0);
            while(res.next()) {
                Vector vx = new Vector();
                for(int i = 1; i <= j; i++) {
                    vx.add(res.getString("kd_menu"));
                    vx.add(res.getString("jenis"));
                    vx.add(res.getString("nama_makanan"));
                    vx.add(res.getString("kuantitas"));
                    vx.add(res.getString("harga"));
                
                }
                df.addRow(vx);
            }
        }catch(SQLException ex){
            System.out.println("SQLException : " +ex.getMessage());
        }
    }//GEN-LAST:event_cariBTActionPerformed

    private void hapusBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBTActionPerformed
        // TODO add your handling code here:
                try{
            con = DriverManager.getConnection(url,"root","");
            stmt = con.createStatement();
            
            
            
            String sql = "Delete from menu where kd_menu ='" +kodeTF.getText() +"'";
            stmt.executeUpdate(sql);
            tampil1();
            kosong();
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
        }catch(SQLException ex){
             System.out.println("SQLException : " +ex.getMessage());
        }
        
        
    }//GEN-LAST:event_hapusBTActionPerformed

    private void hapus2btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapus2btActionPerformed
        // TODO add your handling code here:
        try{
            con = DriverManager.getConnection(url,"root","");
            stmt = con.createStatement();
            
            
            
            String sql = "Delete from transaksi where kd_menu ='" +kd_menu2.getText() +"'";
            stmt.executeUpdate(sql);
            tampil2();
            
            kd_menu2.setText("");
            kuantitas2TF.setText("");
            pemesanTF.setText("");
            no_mejaTF.setText("");        
            totalTF.setText("");
            
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
        }catch(SQLException ex){
             System.out.println("SQLException : " +ex.getMessage());
        }
    }//GEN-LAST:event_hapus2btActionPerformed

    private void data2TBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_data2TBMouseClicked
        int baris = data2TB.rowAtPoint(evt.getPoint());
        String  kd_menu = data2TB.getValueAt(baris, 0).toString();
        kd_menu2.setText(kd_menu);
        String  no_meja = data2TB.getValueAt(baris, 1).toString();
        no_mejaTF.setText(no_meja);
        String  pemesan = data2TB.getValueAt(baris, 2).toString();
        pemesanTF.setText(pemesan);
        String  kuantitas = data2TB.getValueAt(baris, 5).toString();
        kuantitas2TF.setText(kuantitas);

    }//GEN-LAST:event_data2TBMouseClicked

    private void kuantitas2TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kuantitas2TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kuantitas2TFActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        String total_harga = totalTF.getText();
        int total_harga2 = Integer.parseInt(total_harga);
        String uang = uangTF.getText();
        int jumlah_uang = Integer.parseInt(uang);
        
        int keseluruhan = jumlah_uang - total_harga2;
        
        String nilai_akhir = String.valueOf(keseluruhan);
        hasilTF.setText(nilai_akhir);
        
        
        try{
            con = DriverManager.getConnection(url,"root","");
            stmt = con.createStatement();
            
            
            
        String kd_menu="";
        String no_meja="";
        String pemesan ="";
        String jenis="";
        String nama_makanan="";
        String kuantitas="";
        String harga="";
        
                
        String sql2="select *from transaksi";
            res = stmt.executeQuery(sql2);
            
            while(res.next()){
                kd_menu = res.getString("kd_menu");
                no_meja = res.getString("no_meja");
                pemesan = res.getString("pemesan");
                jenis = res.getString("jenis");
                nama_makanan = res.getString("nama_makanan");
                kuantitas = res.getString("kuantitas");
                harga = res.getString("harga");
            }
         System.out.println("ID: " + kd_menu);
                System.out.println("Username: " + no_meja);
                System.out.println("Email: " + pemesan);
                System.out.println();

        
//        String kuantitas_menu="";    
//            
//        String sql_menu="select kuantitas from menu";
//            res = stmt.executeQuery(sql_menu);
//        
//            while(res.next()){
//            kuantitas_menu = res.getString("kuantitas");
//            }
//        int kuantitas_menu2 = Integer.parseInt(kuantitas_menu);
//        int kuantitas2 = Integer.parseInt(kuantitas);
//        int upadate_kuantitas = kuantitas_menu2 - kuantitas2;
//        
//        
//        //update menu
//        String sql_update_menu ="update menu set kuantitas='"+upadate_kuantitas+"'where kd_menu='" +kd_menu+"'";
//           res = stmt.executeQuery(sql_update_menu);
           
           
        String tanggal = (String)tanggalJB.getSelectedItem();
        String bulan = (String)bulanJB.getSelectedItem();
        String tahun = (String)tahunJB.getSelectedItem();
        
        String sql = "insert into laporan values('"+tanggal+"','"+bulan+"','"+tahun+"','"+kd_menu+"','"+no_meja+"','"+jenis+"','"+pemesan+"','"+nama_makanan+"','"+kuantitas+"','"+harga+"')";
            stmt.executeUpdate(sql);
            
            tampil3();
            tampil1();
            
       
        }catch(SQLException ex){
             System.out.println("SQLException : " +ex.getMessage());
        } 
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void cari2BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari2BTActionPerformed
        // TODO add your handling code here:
         try{
            con = DriverManager.getConnection(url,"root","");

            String query = "SELECT * FROM laporan WHERE concat(tanggal, bulan, tahun, kd_menu, jenis,pemesan, nama_makanan, kuantitas, harga) LIKE ? ESCAPE '!'";
            PreparedStatement pstm = con.prepareStatement(query);
            pstm.setString(1, "%" + cari2TF.getText() + "%");
            res = pstm.executeQuery();
            
            ResultSetMetaData results = res.getMetaData();  
            int j = results.getColumnCount();
            
            DefaultTableModel df = (DefaultTableModel)laporan.getModel();
            df.setRowCount(0);
            while(res.next()) {
                Vector vx = new Vector();
                for(int i = 1; i <= j; i++) {
                    vx.add(res.getString("tanggal"));
                    vx.add(res.getString("bulan"));
                    vx.add(res.getString("tahun"));
                    vx.add(res.getString("kd_menu"));
                    vx.add(res.getString("jenis"));
                    vx.add(res.getString("pemesan"));
                    vx.add(res.getString("nama_makanan"));
                    vx.add(res.getString("kuantitas"));
                    vx.add(res.getString("harga"));
                
                }
                df.addRow(vx);
            }
        }catch(SQLException ex){
            System.out.println("SQLException : " +ex.getMessage());
        }
    }//GEN-LAST:event_cari2BTActionPerformed

    private void hapusbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusbtActionPerformed
               try{
            con = DriverManager.getConnection(url,"root","");
            stmt = con.createStatement();
            
            
            
            String sql = "Delete from transaksi where kd_menu ='" +kd_menu2.getText() +"'";
            stmt.executeUpdate(sql);
            tampil2();
            
            kd_menu2.setText("");
            kuantitas2TF.setText("");
            pemesanTF.setText("");
            no_mejaTF.setText("");        
            totalTF.setText("");
            
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
        }catch(SQLException ex){
             System.out.println("SQLException : " +ex.getMessage());
        }
    }//GEN-LAST:event_hapusbtActionPerformed

    private void laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanMouseClicked
                int baris = dataTB.rowAtPoint(evt.getPoint());
        String  kd_menu = dataTB.getValueAt(baris, 0).toString();
        kodeTF.setText(kd_menu);
        kd_menu2.setText(kd_menu);
        String  jenis_hidangan = dataTB.getValueAt(baris, 1).toString();
        jenis_hidanganJB.setSelectedItem(jenis_hidangan);
        String  nama_makanan = dataTB.getValueAt(baris, 2).toString();
        nama_makananTF.setText(nama_makanan);
        String  jumlah = dataTB.getValueAt(baris, 3).toString();
        jumlahTF.setText(jumlah);
        String  harga = dataTB.getValueAt(baris, 4).toString();
        hargaTF.setText(harga);
    }//GEN-LAST:event_laporanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bulanJB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cari2BT;
    private javax.swing.JTextField cari2TF;
    private javax.swing.JButton cariBT;
    private javax.swing.JTextField cariTF;
    private javax.swing.JTable data2TB;
    private javax.swing.JTable dataTB;
    private javax.swing.JButton hapus2bt;
    private javax.swing.JButton hapusBT;
    private javax.swing.JButton hapusbt;
    private javax.swing.JTextField hargaTF;
    private javax.swing.JTextField hasilTF;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> jenis_hidanganJB;
    private javax.swing.JTextField jumlahTF;
    private javax.swing.JTextField kd_menu2;
    private javax.swing.JTextField kodeTF;
    private javax.swing.JTextField kuantitas2TF;
    private javax.swing.JTable laporan;
    private javax.swing.JTextField nama_makananTF;
    private javax.swing.JTextField no_mejaTF;
    private javax.swing.JTextField pemesanTF;
    private javax.swing.JComboBox<String> tahunJB;
    private javax.swing.JButton tambahBT;
    private javax.swing.JComboBox<String> tanggalJB;
    private javax.swing.JTextField totalTF;
    private javax.swing.JTextField uangTF;
    // End of variables declaration//GEN-END:variables
}
